title: Custom Metadata Scraper
description: Select the document data you would like to retrieve
type: object
documents:
  - selected
  - query
properties:
  ID:
    title: ID
    type: boolean
  TITLE:
    title: Title
    type: boolean
  PRIVACYLEVEL:
    title: Access Level
    type: boolean
  ASSETURL:
    title: Asset URL
    type: boolean
  CONTRIBUTOR:
    title: Contributor
    type: boolean
  CREATEDATDATE:
    title: Created at Date
    type: boolean
  DESCRIPTION:
    title: Description
    type: boolean
  FULLTEXTURL:
    title: Full Text URL
    type: boolean
  PDFURL:
    title: PDF URL
    type: boolean
  PAGECOUNT:
    title: Page Count
    type: boolean
  TAGS:
    title: Tags
    type: boolean
  KEYVALUEPAIRS:
    title: Key/Value Pairs
    type: boolean
categories:
  - export
