# The title is the title of your Add-On
title: Custom Metadata Scraper
# The description will be shown above the form when activating the Add-On
description: Select the document data you would like to retrieve
# Type should always be object
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the currently selected documents
  - selected
  - query
# Properties are the fields for your form
properties:
  # the key is the name of the variable that will be returned to your code
  ID:
    title: ID
    type: boolean

  TITLE:
    title: Title
    type: boolean

  PRIVACYLEVEL:
    title: Privacy Level
    type: boolean

  ASSETURL:
    title: Asset-Url
    type: boolean

  CONTRIBUTOR:
    title: Contributor
    type: boolean

  CREATEDATDATE:
    title: Created at Date
    type: boolean

  DESCRIPTION:
    title: Description
    type: boolean

  FULLTEXTURL:
    title: Full Text Url
    type: boolean

  PDFURL:
    title: Pdf-Url
    type: boolean

  PAGECOUNT:
    title: Page Count
    type: boolean

  TAGS:
    title: Tags
    type: boolean

  KEYVALUEPAIRS:
    title: Key Value Pairs
    type: boolean
categories:
  - export
