title: Custom Metadata Scraper
description: Export a customized list of metadata from a set of documents. 
type: object
documents:
  - selected
  - query
properties:
  ID:
    title: ID
    type: boolean
  TITLE:
    title: Title
    type: boolean
  ACCESSLEVEL:
    title: Access Level
    type: boolean
  CANONICALURL:
    title: Canonical URL (The URL where the document is hosted on DocumentCloud)
    type: boolean
  CONTRIBUTOR:
    title: Contributor
    type: boolean
  CREATEDATDATE:
    title: Created at Date
    type: boolean
  DESCRIPTION:
    title: Description
    type: boolean
  FULLTEXTURL:
    title: Full Text URL
    type: boolean
  PDFURL:
    title: PDF URL
    type: boolean
  PAGECOUNT:
    title: Page Count
    type: boolean
  TAGS:
    title: Tags
    type: boolean
  KEYVALUEPAIRS:
    title: Key/Value Pairs
    type: boolean
categories:
  - export
